#!/usr/bin/env bash
# OpenSLR 28 (RIRS_NOISES), the licence-clean part only, as 16 kHz FLAC.
#
# Kept:
#   simulated_rirs/     image-method RIRs generated by the Kaldi authors
#                       (OpenSLR 26 / 28, Apache 2.0); 10 of the 100 RIRs
#                       of each of the 600 rooms.
#   pointsource_noises/ the Freesound part of MUSAN, every file marked
#                       Public Domain on Freesound (its LICENSE file).
# Dropped:
#   real_rirs_isotropic_noises/  it bundles RWCP (OpenSLR 13: "research and
#                       development use only"), AIR (licence not stated) and
#                       REVERB challenge RIRs, so the Apache 2.0 label on the
#                       bundle does not hold for this folder.
#
# Usage: fetch_rirs_noises.sh [DEST=D:/datasets/rirs_noises]
set -euo pipefail
DEST=${1:-D:/datasets/rirs_noises}
URL=https://openslr.elda.org/resources/28/rirs_noises.zip
TMP=$DEST/_tmp
mkdir -p "$TMP"
ZIP=$TMP/rirs_noises.zip
[ -f "$ZIP.done" ] || { curl -s -C - -o "$ZIP" "$URL"; touch "$ZIP.done"; }

cd "$TMP"
unzip -o -q "$ZIP" 'RIRS_NOISES/README' 'RIRS_NOISES/pointsource_noises/*' 'RIRS_NOISES/simulated_rirs/README' \
    'RIRS_NOISES/simulated_rirs/*/room_info' 'RIRS_NOISES/simulated_rirs/*/rir_list'
# Ten RIRs per simulated room: RIR names are Room<rrr>-<nnnnn>.wav.
# (this unzip's '*' does not cross '/')
unzip -o -q "$ZIP" 'RIRS_NOISES/simulated_rirs/*/*/Room*-0000[1-9].wav' 'RIRS_NOISES/simulated_rirs/*/*/Room*-00010.wav'

to_flac() {  # wav tree -> flac tree
    local src=$1 dst=$2
    find "$src" -name '*.wav' | while read -r f; do
        rel=${f#"$src"/}
        out=$dst/${rel%.wav}.flac
        mkdir -p "$(dirname "$out")"
        [ -f "$out" ] || ffmpeg -nostdin -hide_banner -loglevel error -i "$f" -ac 1 -ar 16000 -c:a flac "$out"
    done
}
to_flac RIRS_NOISES/pointsource_noises "$DEST/pointsource_noises"
to_flac RIRS_NOISES/simulated_rirs "$DEST/simulated_rirs"
cp RIRS_NOISES/README "$DEST/README"
cp RIRS_NOISES/pointsource_noises/LICENSE RIRS_NOISES/pointsource_noises/noise_list "$DEST/pointsource_noises/"
cp RIRS_NOISES/simulated_rirs/README "$DEST/simulated_rirs/"
for r in smallroom mediumroom largeroom; do cp RIRS_NOISES/simulated_rirs/$r/room_info "$DEST/simulated_rirs/$r/"; done

find "$DEST/simulated_rirs" -name '*.flac' | sort > "$DEST/rirs.list"
find "$DEST/pointsource_noises" -name '*.flac' | sort > "$DEST/noises.list"
cd "$DEST" && rm -rf "$TMP"
echo "rirs: $(wc -l < rirs.list), noises: $(wc -l < noises.list), $(du -sh . | cut -f1)"
