#pragma once

#include "brosoundml/audio.h"
#include "brosoundml/higgs_codec.h"

#include <brotensor/tensor.h>

#include <cstdint>
#include <functional>
#include <memory>
#include <string>
#include <vector>

namespace brosoundml {

// ─── OmniVoice (masked-diffusion, 600+ languages, 25 Hz x 8 codebooks) ──────
//
// OmniVoice (k2-fsa, 2026) is a zero-shot TTS whose language model is a stock
// Qwen3-0.6B trunk with the text head replaced by eight audio heads: one
// 1025-way classifier per RVQ codebook (1024 codes + a MASK id). Speech is
// generated by masked diffusion, not autoregression. Pipeline — the order
// brosoundml drives it:
//
//   1. Text        text -> Qwen BPE ids (brolm::qwen tokenizer over the
//                  shipped tokenizer.json; non-verbal tags such as [laughter]
//                  tokenize standalone). The prompt is
//                    [<|denoise|>] <|lang_start|>{lang|None}<|lang_end|>
//                    <|instruct_start|>{instruct|None}<|instruct_end|>
//                    <|text_start|>{ref_text + " " + text}<|text_end|>
//                  followed by the reference audio codes (8 x T_ref, embedded
//                  as the sum of the eight codebook embeddings) and a block of
//                  T_target MASK frames.
//   2. Duration    T_target is NOT predicted by the model: a rule-based
//                  per-script character-weight estimator sets it, scaled by the
//                  reference's tokens-per-character (or a fixed fallback when
//                  there is no reference). `speed` divides it; `duration`
//                  overrides it outright.
//   3. LM          num_steps forwards over two packed rows — the conditional
//                  prompt and a text-free unconditional prompt for
//                  classifier-free guidance — with fully bidirectional
//                  attention (no KV cache is possible; on CUDA one graph is
//                  captured per shape and replayed every step). Per step, each
//                  masked (codebook, frame) position gets CFG log-probs, an
//                  argmax (or a top-10% Gumbel sample when class_temperature
//                  > 0), a confidence = max log-prob minus layer_penalty *
//                  codebook, plus Gumbel noise / position_temperature; the k
//                  highest-scoring positions are unmasked, k following a
//                  t_shift-warped linear schedule.
//   4. Codec       HiggsAudio v2 (higgs_codec.h): 8 codes / frame -> 24 kHz.
//   5. Post        optional silence trimming, RMS match to the reference (or
//                  peak-normalise without one), fade + pad.
//
// Long text (> audio_chunk_threshold seconds estimated) is split at
// punctuation into ~audio_chunk_duration chunks, generated one at a time
// (the reference — or, without one, the first chunk's own output — conditions
// every chunk), and cross-faded.
//
// Voice cloning is in-context: the reference clip is encoded to codes by the
// codec encoder (HuBERT + DAC) and placed in the prompt with its transcript.
// Voice design is a fixed-vocabulary instruct (gender / age / pitch / whisper /
// accent / dialect; see instruct_attributes()). With neither, the model picks
// a voice.
//
// brotensor op coverage: rms_norm, rope, GQA varlen flash attention (non-
// causal), silu/SwiGLU, embedding_lookup, linear (FP32 or BF16 weights), and
// the two masked-diffusion ops (masked_diffusion_scores / _commit) plus
// top_k_rows for the per-step unmask select. See docs/omnivoice.md.

// The Qwen3 trunk + audio heads, from config.json's llm_config + top level.
struct OmniVoiceLmConfig {
    int   hidden_size         = 1024;
    int   intermediate_size   = 3072;
    int   num_hidden_layers   = 28;
    int   num_attention_heads = 16;
    int   num_key_value_heads = 8;
    int   head_dim            = 128;
    float rms_norm_eps        = 1e-6f;
    float rope_theta          = 1000000.0f;
    int   vocab_size          = 151676;  // text vocab (embed_tokens rows)

    int num_codebooks    = 8;
    int audio_vocab_size = 1025;         // 1024 codes + MASK
    int audio_mask_id    = 1024;
    std::vector<int> codebook_weights;   // audio_codebook_weights (training loss weights; informational)
};

// Top-level OmniVoice config, read from config.json + tokenizer_config.json by
// OmniVoice::load.
struct OmniVoiceConfig {
    OmniVoiceLmConfig lm;
    HiggsCodecConfig  codec;
    int sample_rate = 24000;
    int frame_rate  = 25;

    // Prompt framing specials (text vocab ids), resolved from the tokenizer.
    int denoise_id        = -1;
    int lang_start_id     = -1, lang_end_id     = -1;
    int instruct_start_id = -1, instruct_end_id = -1;
    int text_start_id     = -1, text_end_id     = -1;
    int eos_id = -1;   // <|im_end|>
    int pad_id = -1;   // <|endoftext|>
};

// Storage precision for the LM's linear weights (the checkpoint is F32).
//   FP32 — widen everything (the default). CPU and CUDA agree to float
//          round-off; the fixture tests gate this mode.
//   BF16 — narrow the projection / MLP / audio_heads weights to BF16 and run
//          those GEMMs on BF16 operands (each linear's input is cast to BF16,
//          accumulation is FP32, the product is widened back), which is what
//          puts them on the tensor cores; the residual stream, norms, RoPE,
//          attention, SwiGLU product, embeddings and scores stay FP32. CPU
//          emulates the same rounding with FP32 dots (a correctness path,
//          not a fast one). The discrete stream may differ from FP32 at
//          near-ties.
enum class OmniVoicePrecision { FP32, BF16 };

// A reference voice: the codec codes of a clip plus its transcript and RMS —
// everything the prompt needs, and everything a clone needs to persist.
// Upstream's VoiceClonePrompt. Serialised by save()/load() as a small
// self-describing binary ("OVCP" magic; see docs/omnivoice.md).
struct OmniVoicePrompt {
    std::vector<int32_t> codes;   // num_codebooks * num_frames, codes[q * num_frames + t]
    int         num_frames = 0;
    std::string text;             // transcript of the clip
    float       rms = 0.0f;       // RMS of the (preprocessed) clip, for output loudness matching

    void save(const std::string& path) const;
    static OmniVoicePrompt load(const std::string& path);
};

// Generation parameters. Defaults mirror upstream OmniVoiceGenerationConfig.
struct OmniVoiceParams {
    // ── masked-diffusion schedule ──
    int   num_steps            = 32;    // forwards per chunk (16 is acceptable)
    float t_shift              = 0.1f;  // schedule warp: t' = s*t / (1 + (s-1)*t)
    float guidance_scale       = 2.0f;  // CFG weight; 0 = conditional only (one row)
    float layer_penalty        = 5.0f;  // confidence -= codebook * layer_penalty
    float position_temperature = 5.0f;  // Gumbel noise scale on the unmask order
    float class_temperature    = 0.0f;  // > 0: top-10% Gumbel sample per position
    bool  gumbel_noise         = true;  // false: constant uniforms (deterministic order)
    std::uint64_t seed         = 0;     // host RNG seed for the Gumbel uniforms

    // ── length ──
    float speed    = 1.0f;   // divides the estimated frame count
    float duration = 0.0f;   // seconds; > 0 fixes the frame count outright

    // ── conditioning ──
    std::string language;    // "" -> "None"; see languages()
    std::string instruct;    // "" -> "None"; validated voice-design attributes
    bool denoise = true;     // prepend <|denoise|> when a prompt is present

    // ── pre/post-processing (upstream defaults) ──
    bool  preprocess_prompt    = true;
    bool  postprocess_output   = true;   // silence trim + RMS/peak + fade + pad
    float audio_chunk_duration  = 15.0f; // seconds per long-form chunk
    float audio_chunk_threshold = 30.0f; // chunk when the estimate exceeds this
    float pad_duration  = 0.1f;
    float fade_duration = 0.1f;
};

// Inpainting / re-roll seam: a starting token grid for generate_codes(). Any
// position with keep[i] != 0 is fixed at tokens[i] for the whole schedule;
// the rest start masked. Both arrays are num_codebooks * num_frames laid out
// [q * num_frames + t]. Regenerate one time span, keep codebook 0 and re-roll
// the acoustic codebooks, or splice takes — all through this one input.
struct OmniVoiceInit {
    std::vector<int32_t> tokens;
    std::vector<uint8_t> keep;
};

// Per-step observation for a lab: the token grid so far (audio_mask_id where
// still masked), this step's scores (-inf where already fixed), this step's raw
// confidence, and how many positions were just unmasked. Pointers are valid
// only during the callback.
//
// scores vs confidence — they are not the same signal:
//   scores      the selection score the op ranked positions by: the raw
//               confidence minus codebook * layer_penalty, then divided by
//               position_temperature with Gumbel noise added when it is > 0,
//               and -inf at every position that is already fixed. It answers
//               "which cell won this step", and its magnitudes are dominated
//               by the per-codebook penalty and the noise.
//   confidence  the model's raw max CFG log-prob at the position, before the
//               penalty and before any noise, written for EVERY position —
//               already-unmasked ones included, since the model predicts every
//               target position on every forward. It answers "how sure was the
//               model here", which is what a heat map wants.
//
// `step` restarts at 0 for every chunk of a long-form synthesize; `chunk` says
// which chunk this is (0-based) and `num_chunks` how many there are in total
// (1 for an unchunked run and for generate_codes).
struct OmniVoiceStep {
    int step = 0, num_steps = 0;
    int chunk = 0, num_chunks = 1;    // long-form chunk index / count
    int num_frames = 0, num_codebooks = 0;
    int unmasked = 0;                 // positions fixed this step
    const int32_t* tokens = nullptr;  // num_codebooks * num_frames
    const float*   scores = nullptr;  // num_codebooks * num_frames
    const float*   confidence = nullptr;  // num_codebooks * num_frames, raw
};
using OmniVoiceStepFn = std::function<void(const OmniVoiceStep&)>;

// Optional diagnostics from a synthesis.
struct OmniVoiceTrace {
    std::vector<int32_t> text_ids;       // the conditional prompt's text ids
    int num_frames = 0;                  // frames generated (all chunks)
    std::vector<int32_t> codes;          // num_codebooks * num_frames, [q * num_frames + t]
    std::vector<int32_t> unmask_step;    // step at which each position was fixed (-1 = initial)
    // Raw max CFG log-prob at each position — the same signal as
    // OmniVoiceStep::confidence, sampled at the step that position was
    // committed (so it pairs cell-for-cell with unmask_step). A position an
    // init grid kept, which is therefore never committed, carries its last
    // step's confidence instead. Same layout as codes; empty if the run was
    // cancelled before its first step.
    std::vector<float>   confidence;
    std::vector<int32_t> chunk_frames;   // per-chunk frame counts (1 entry when unchunked)
    double lm_seconds = 0, codec_seconds = 0;
};

// The pipeline.
class OmniVoice {
public:
    OmniVoice();
    ~OmniVoice();
    OmniVoice(OmniVoice&&) noexcept;
    OmniVoice& operator=(OmniVoice&&) noexcept;
    OmniVoice(const OmniVoice&) = delete;
    OmniVoice& operator=(const OmniVoice&) = delete;

    // Load config.json, tokenizer.json, model.safetensors and audio_tokenizer/
    // from `model_dir`, placing weights on `device`. `precision` selects the LM
    // linear-weight storage; the codec is FP32 regardless. With
    // `codec_decoder_only` the codec encoder + HuBERT are skipped (create_prompt
    // / encode_audio then throw). Throws std::runtime_error on a missing /
    // malformed model.
    void load(const std::string& model_dir,
              brotensor::Device device = brotensor::Device::CPU,
              OmniVoicePrecision precision = OmniVoicePrecision::FP32,
              bool codec_decoder_only = false);

    // Text -> 24 kHz PCM. `prompt` (nullable) clones that voice; otherwise the
    // voice comes from params.instruct or the model's own choice. Long text is
    // chunked and cross-faded. `cancel` is polled once per diffusion step; on
    // cancel an empty buffer is returned. `on_step` (nullable) observes every
    // step. Throws if no model is loaded or `text` is empty.
    AudioBuffer synthesize(const std::string& text,
                           const OmniVoiceParams& params = {},
                           const OmniVoicePrompt* prompt = nullptr,
                           const CancelCheck& cancel = {},
                           OmniVoiceTrace* trace = nullptr,
                           const OmniVoiceStepFn& on_step = {}) const;

    // The LM alone, one chunk, no chunking / post-processing: run the masked-
    // diffusion schedule for `text` at exactly `num_frames` frames (<= 0 ->
    // estimate_frames) and return the num_codebooks * num_frames codes
    // ([q * num_frames + t]). `init` (nullable) seeds the grid for inpainting.
    // Feed the result to decode_codes(). The seam a lab drives.
    std::vector<int32_t> generate_codes(const std::string& text,
                                        int num_frames,
                                        const OmniVoiceParams& params = {},
                                        const OmniVoicePrompt* prompt = nullptr,
                                        const OmniVoiceInit* init = nullptr,
                                        const CancelCheck& cancel = {},
                                        OmniVoiceTrace* trace = nullptr,
                                        const OmniVoiceStepFn& on_step = {}) const;

    // The duration rule: frames the pipeline would generate for `text` given
    // `prompt` (nullable) and params.speed / params.duration.
    int estimate_frames(const std::string& text,
                        const OmniVoiceParams& params = {},
                        const OmniVoicePrompt* prompt = nullptr) const;

    // Build a voice prompt from a reference clip and its transcript: the
    // upstream preprocessing (RMS boost, trim to <= 20 s at the widest silence,
    // silence removal, frame alignment, terminal punctuation) when
    // `preprocess`, then the codec encoder. `ref` is resampled to 24 kHz mono.
    // Throws if the codec encoder is not loaded or `ref` is empty.
    OmniVoicePrompt create_prompt(const AudioBuffer& ref, const std::string& ref_text,
                                  bool preprocess = true) const;

    // The codec on its own (see HiggsCodec). Codes are [q * num_frames + t].
    AudioBuffer decode_codes(const std::vector<int32_t>& codes, int num_frames) const;
    std::vector<int32_t> encode_audio(const AudioBuffer& audio, int* num_frames_out = nullptr) const;

    // Tokenize text exactly as the prompt does (non-verbal tags standalone).
    std::vector<int32_t> tokenize(const std::string& text) const;

    // Language names accepted by OmniVoiceParams::language (upstream lang_map).
    std::vector<std::string> languages() const;

    // Voice-design vocabulary: category -> allowed values (gender, age, pitch,
    // style, accent, dialect). An instruct is a comma-separated pick of at
    // most one value per category; anything else throws from synthesize.
    struct InstructCategory { std::string name; std::vector<std::string> values; };
    std::vector<InstructCategory> instruct_attributes() const;

    // The non-verbal tags the tokenizer treats as one unit ("[laughter]", ...).
    std::vector<std::string> nonverbal_tags() const;

    const OmniVoiceConfig& config() const;
    bool loaded() const;
    brotensor::Device device() const;

private:
    struct Impl;
    std::unique_ptr<Impl> impl_;
};

}  // namespace brosoundml
