// GENERATED by tools/build_pos_dataset.py — do not edit.
// Tag inventory derived from UD treebanks: EWT,GUM
#pragma once
#include <cstdint>

namespace brosoundml::g2p {

enum class PosTag : std::uint8_t {
    P_DOLLAR,  // $
    P_QUOTE_QUOTE,  // ''
    P_COMMA,  // ,
    P_LRB,  // -LRB-
    P_RRB,  // -RRB-
    P_DOT,  // .
    P_COLON,  // :
    ADD,  // ADD
    AFX,  // AFX
    CC,  // CC
    CD,  // CD
    DT,  // DT
    EX,  // EX
    FW,  // FW
    GW,  // GW
    HYPH,  // HYPH
    IN,  // IN
    JJ,  // JJ
    JJR,  // JJR
    JJS,  // JJS
    LS,  // LS
    MD,  // MD
    NFP,  // NFP
    NN,  // NN
    NNP,  // NNP
    NNPS,  // NNPS
    NNS,  // NNS
    PDT,  // PDT
    POS,  // POS
    PRP,  // PRP
    PRP_,  // PRP$
    RB,  // RB
    RBR,  // RBR
    RBS,  // RBS
    RP,  // RP
    SYM,  // SYM
    TO,  // TO
    UH,  // UH
    VB,  // VB
    VBD,  // VBD
    VBG,  // VBG
    VBN,  // VBN
    VBP,  // VBP
    VBZ,  // VBZ
    WDT,  // WDT
    WP,  // WP
    WP_,  // WP$
    WRB,  // WRB
    P_BACKTICK_BACKTICK,  // ``
};

inline constexpr int NUM_TAGS = 49;

inline constexpr const char* kPosTagNames[NUM_TAGS] = {
    "$",
    "''",
    ",",
    "-LRB-",
    "-RRB-",
    ".",
    ":",
    "ADD",
    "AFX",
    "CC",
    "CD",
    "DT",
    "EX",
    "FW",
    "GW",
    "HYPH",
    "IN",
    "JJ",
    "JJR",
    "JJS",
    "LS",
    "MD",
    "NFP",
    "NN",
    "NNP",
    "NNPS",
    "NNS",
    "PDT",
    "POS",
    "PRP",
    "PRP$",
    "RB",
    "RBR",
    "RBS",
    "RP",
    "SYM",
    "TO",
    "UH",
    "VB",
    "VBD",
    "VBG",
    "VBN",
    "VBP",
    "VBZ",
    "WDT",
    "WP",
    "WP$",
    "WRB",
    "``",
};

// Universal Dependencies v2 UPOS — fixed inventory, 17 tags.
enum class UPosTag : std::uint8_t {
    ADJ,
    ADP,
    ADV,
    AUX,
    CCONJ,
    DET,
    INTJ,
    NOUN,
    NUM,
    PART,
    PRON,
    PROPN,
    PUNCT,
    SCONJ,
    SYM,
    VERB,
    X,
};

inline constexpr std::uint32_t NUM_UPOS_TAGS = 17;

inline constexpr const char* kUPosTagNames[NUM_UPOS_TAGS] = {
    "ADJ",
    "ADP",
    "ADV",
    "AUX",
    "CCONJ",
    "DET",
    "INTJ",
    "NOUN",
    "NUM",
    "PART",
    "PRON",
    "PROPN",
    "PUNCT",
    "SCONJ",
    "SYM",
    "VERB",
    "X",
};

}  // namespace brosoundml::g2p
